sonar.projectKey=mern-cicd-project
sonar.projectName=MERN CI/CD Project
sonar.projectVersion=1.0

sonar.sources=backend,frontend

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.sourceEncoding=UTF-8

sonar.javascript.node.maxspace=4096